<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:pay="urn:unipay"
    targetNamespace="urn:unipay"
    name="PaymentsService">

    <!-- types -->

    <types>

        <xsd:schema targetNamespace="urn:unipay">

            <xsd:element name="charge">

                <xsd:complexType>

                    <xsd:sequence>

                        <xsd:element
                            name="cardToken"
                            type="xsd:string"/>

                        <xsd:element
                            name="amount"
                            type="xsd:decimal"/>

                        <xsd:element
                            name="currency"
                            type="xsd:string"/>

                    </xsd:sequence>

                </xsd:complexType>

            </xsd:element>


            <xsd:element name="chargeResult">

                <xsd:complexType>

                    <xsd:sequence>

                        <xsd:element
                            name="transactionId"
                            type="xsd:string"/>

                        <xsd:element
                            name="status"
                            type="xsd:string"/>

                    </xsd:sequence>

                </xsd:complexType>

            </xsd:element>

        </xsd:schema>

    </types>


    <!-- message -->

    <message name="chargeRequest">

        <part
            name="body"
            element="pay:charge"/>

    </message>


    <message name="chargeResponse">

        <part
            name="body"
            element="pay:chargeResult"/>

    </message>


    <!-- port type -->

    <portType name="Payments">

        <operation name="charge">

            <input message="pay:chargeRequest"/>

            <output message="pay:chargeResponse"/>

        </operation>

    </portType>


    <!-- binding -->

    <binding
        name="PaymentsSOAP"
        type="pay:Payments">

        <soap:binding
            transport="http://schemas.xmlsoap.org/soap/http"
            style="document"/>

        <operation name="charge">

            <soap:operation
                soapAction="urn:unipay:charge"/>

            <input>

                <soap:body use="literal"/>

            </input>

            <output>

                <soap:body use="literal"/>

            </output>

        </operation>

    </binding>


    <!-- service and port -->

    <service name="PaymentsService">

        <port
            name="PaymentsSOAP"
            binding="pay:PaymentsSOAP">

            <soap:address
                location="https://api.unipay.example/pay"/>

        </port>

    </service>

</definitions>